version: '2.6'
services:
  go:
    image: golang:1.19-rc
    ports:
      - 3000:3000
    volumes:
      - ./data/go:/go-work
    working_dir: /go-work
    tty: true
  next-js:
    image: node:18.6.0-alpine3.15
    ports:
      - 3001:3001
    volumes:
      - ./data/next-js:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true